language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11

service:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `myapp_test`;'

script: mvn clean install

cache:
  directories:
  - node_modules

after_success:
  - mvn clean test jacoco:report coveralls:report
