language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11

service:
  - mysql

before_install:
  - mysql -e 'CREATE SCHEMA IF NOT EXISTS `fullstack-ecommerce`; CREATE USER 'ecommerce'@'localhost' IDENTIFIED BY 'ecommerce'; GRANT ALL PRIVILEGES ON * . * TO 'ecommerce'@'localhost';'

script: mvn clean install

cache:
  directories:
  - node_modules

after_success:
  - mvn clean test jacoco:report coveralls:report
