language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11

service:
  - mysql

before_install:
  - mysql -u root -e 'CREATE SCHEMA IF NOT EXISTS `full-stack-ecommerce`;'
  - mysql -u root -e "CREATE USER IF NOT EXISTS 'ecommerce'@'localhost' IDENTIFIED BY 'ecommerce';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'ecommerce'@'localhost';"
  - mysql -u root -e "USE `full-stack-ecommerce`;"

script: mvn clean install

cache:
  directories:
  - node_modules

after_success:
  - mvn clean test jacoco:report coveralls:report
